[package]
name = "gmsv_serverstat"
version = "0.2.5"
authors = ["William Venner <william@venner.io>"]
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = 'thin'
codegen-units = 1

[features]
default = []
lua-api = ["crossbeam"]

[dependencies]
gmod = "17"
sysinfo = "0.38"
metrics = "0.24"
metrics-exporter-prometheus = { version = "0.18", default-features = false, features = ["http-listener"] }
crossbeam = { version = "0.8", default-features = false, features = ["crossbeam-channel", "std"], optional = true }
